# Generated by Django 2.0.4 on 2018-06-05 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('bureau', models.TextField()),
                ('os', models.TextField()),
                ('host', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('batiment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='geeps.Batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Logiciel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('logiciel', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='geeps.Logiciel')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='logiciel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='geeps.Logiciel'),
        ),
        migrations.AddField(
            model_name='demande',
            name='version',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='geeps.Version'),
        ),
    ]
