# Generated by Django 2.0.4 on 2018-06-11 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeps', '0003_auto_20180606_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='email',
            field=models.EmailField(default='Unknown', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric', regex='r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)"')]),
        ),
    ]
