# Generated by Django 2.0.4 on 2018-06-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeps', '0004_auto_20180611_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='email',
            field=models.EmailField(default='Unknown', max_length=100),
        ),
    ]
